---
title: "Bumps"
author: "Uwin Abeywikrama"
date: "July 3, 2018"
output: html_document
---


```{r}
library("rjson")
json_file1 <- "j7Uduwila1PotholeModel.json"
json_data1 <- fromJSON(file=json_file1)

vector_acceY <- numeric()
vector_acceY_raw <- numeric()
vector_time <- numeric()
vector_anomaly <- numeric()

vector_anomalyTimes <- c(1530858189559, 1530858190359, 1530858194360, 1530858195359, 1530858205179, 1530858205979, 1530858216399,
                 1530858217099, 1530858220607, 1530858222019, 1530858232136, 1530858233140, 1530858267293, 1530858267900)

for (item in json_data1){

  vector_acceY <- c(vector_acceY, item$acceY)
  vector_time <- c(vector_time, item$time)
  if(is.element(item$time, vector_anomalyTimes)){
    vector_anomaly <- c(vector_anomaly, 1)
  }
  else{
     vector_anomaly <- c(vector_anomaly, 0)
  }




}


```
```{r}
library(plotly)
time_accY = data.frame(time = vector_time, acceY = vector_acceY)
time_anomaly = data.frame(time = vector_time, anomaly = vector_anomaly)
theme_set(theme_classic())
p1 <- plot_ly(time_accY, x = ~time, y = ~acceY, type = "area") %>%
  add_lines(name = ~"acceY")
p2 <- plot_ly(time_anomaly, x = ~time, y = ~anomaly, type = "bar") %>%
  add_lines(name = ~"Anomaly")
p <- subplot(p1, p2, nrows = 2,shareX = TRUE)
p
```